# Parameters for policy to learn weights per hash based on separability
fit_params:
  topk: 5
  policy: cka # cka or rayleigh
  normalize: true # ensure weights of kernels sum to 1
# Shared preproc ops. will create one kernel for every combination of these
shared_preproc:
  edges: [false, true]
  log_polar: [false, true]
# Feature extractors
kernels:
  - class: CornerCountHash
    params:
      img_size: 128
  - class: ColorHash
    params:
      img_size: 64
  - class: WaveletHash
    params:
      hash_size: 8
      scale: 4
      thresh: median
      blur: 3
  - class: PerceptualHash
    params:
      hash_size: 8
      highfreq_factor: 4
      thresh: median # true phash
  - class: PerceptualHash
    params:
      hash_size: 8
      highfreq_factor: 4
      thresh: mean # phash simple
  - class: PixelHash
    params:
      hash_size: 8
      thresh: mean # ahash
  - class: PixelHash
    params:
      hash_size: 8
      thresh: median # mhash
  - class: HDiffHash
    params:
      hash_size: 8
  - class: VDiffHash
    params:
      hash_size: 8

  #- class: GaborHash
  #  params:
  #    img_size: 32
  #    model_path: models/gabor_filter-7_pool-2_energy-abs.onnx
  #    thresh: mean
  #- class: GaborHash
  #  params:
  #    img_size: 32
  #    model_path: models/gabor_filter-7_pool-2_energy-square.onnx
  #    thresh: mean
  #- class: SqueezeNetHash
  #  params:
  #    img_size: 32
  #    model_path: models/squeezenet1_1_1-layer_input-32.onnx
  #    thresh: mean
    #- class: LineCountHash
  #  params:
  #    img_size: 32
  #- class: HOGHash
  #  params:
  #    img_size: 64
  #    num_bins: 4
  #    thresh: mean
  #- class: HOGHash
  #  params:
  #    img_size: 64
  #    num_bins: 2
  #    thresh: mean